import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins, Montserrat, Bodoni_Moda } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-heading' });
const poppins = Poppins({ 
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  variable: '--font-subtitle'
});
const bodoni = Bodoni_Moda({ 
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-body'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${montserrat.variable} ${poppins.variable} ${bodoni.variable} font-body`}
      >
        {children}
      </body>
    </html>
  );
}
